### ISSUE TITLE
The feature 'sandbox selector' is not supported in the declared launch 

### ISSUE THREAD

**Issue by rainy-me** [google-github-actions/deploy-cloudrun#26]
Hello, I've been using this action since last week and everything worked just fine. But since today some errors happen and fail to depoly the image.

**Expected behavior**

It depolys new cloud run images successfully.

**Observed behavior**

```
Run google-github-actions/deploy-cloudrun@v0.2.0
  with:
    service: ***
    image: asia.gcr.io/***/***:299faf0ea2878d743045b2ab96914290c774e633
    region: asia-northeast1
  env:
    PROJECT_ID: ***
    SERVICE: ***
    SA_KEY: ***
    REGION: asia-northeast1
    IMAGE: asia.gcr.io/***/***
    CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
    GCLOUD_PROJECT: ***
    GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/***/***/0dfa6524-a860-4607-bebf-c46a81b38eaa
Setting project Id from $GCLOUD_PROJECT
Creating a service revision...
Error: Error: The feature 'sandbox selector' is not supported in the declared launch stage on resource ***. The launch stage annotation should be specified at least as BETA. Please visit https://cloud.google.com/run/docs/troubleshooting#launch-stage-validation for in-depth troubleshooting documentation.
Error: The feature 'sandbox selector' is not supported in the declared launch stage on resource ***. The launch stage annotation should be specified at least as BETA. Please visit https://cloud.google.com/run/docs/troubleshooting#launch-stage-validation for in-depth troubleshooting documentation.
```

I visited the  https://cloud.google.com/run/docs/troubleshooting#launch-stage-validation page but found nothing I can do as a user of this action.

### Reproduction

**Action YAML**

https://github.com/rainy-me/tsukiyo/blob/master/.github/workflows/depoly-backend.yml

```yaml
name: Deploy Backend Cloud Run

on:
  push:
    branches:
      - master

# adapted form https://github.com/google-github-actions/deploy-cloudrun/blob/main/.github/workflows/example-workflow.yaml
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: ${{ secrets.GCP_SERVICE }}
  SA_KEY: ${{ secrets.GCP_SA_KEY }}
  REGION: asia-northeast1
  IMAGE: asia.gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_SERVICE }}

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |
          docker pull ${{ env.IMAGE }}-cache || true
          docker build . -t ${{ env.IMAGE }}:${{  github.sha }} -f Dockerfile.prod --cache-from=${{ env.IMAGE }}-cache
          docker push ${{ env.IMAGE }}:${{  github.sha }} || true
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ env.SERVICE }}
          image: ${{ env.IMAGE }}:${{ github.sha }}
          region: ${{ env.REGION }}

      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              username: 'deploy-backend',
              icon_emoji: ':actix:',
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `Deploy backend done in ${process.env.AS_TOOK} :actix:`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

**Repository**

https://github.com/rainy-me/tsukiyo

specifically the `depoly-backend` action

**Additional information**

**Comment by averikitsch** [comment]
Hi @rainy-me , I wouldn't expect this error when you are not using the `metadata` input and I am not able to reproduce. It also doesn't seem like updates to the action is causing this. My assumption is that your container is not starting correctly. Can you go the the Cloud Run UI to check the logs for more information? Can you also try to deploy this manually?

**Comment by rainy-me** [comment]
Thanks for your quick response :) I tried to deploy a new version but this issue still happens. The most wired part is it worked before but stop working all of a sudden.

>  when you are not using the metadata input

I have some configurations set in the  Cloud Run console like `max instances`, but not putting them explicitly in the `metadata` field in of this action.  Should I include them in the action yml too?

> container is not starting correctly
> check the logs for more information

It seems that the action failed before creating a cloudrun new revision. The only log I can found is something similar. If the container is not starting correctly, I expect to see logs show a new revision is created by failed to start. Is that correct?

![photo_2021-01-30_16-05-31](https://user-images.githubusercontent.com/26110087/106349890-fff9f880-6314-11eb-9f37-42928393b5e5.jpg)

I can find built and pushed container in the previous step in the container registry though.

> Can you also try to deploy this manually

I'm able to deploy it manually from the console.

**Comment by rickkln** [comment]
Any updates on this? Also started seeing this on one of our services, though not all. Not sure why as all the services use this action in the same way. It happens every time on the service where there is a problem so perhaps something in the config on GCP side that can be changed?

**Comment by averikitsch** [comment]
> Any updates on this? Also started seeing this on one of our services, though not all. Not sure why as all the services use this action in the same way. It happens every time on the service where there is a problem so perhaps something in the config on GCP side that can be changed?

I believe PR #30 should fix this due to additional annotations added on the GCP side.

**Comment by rickkln** [comment]
Thank you!

**Comment by rickkln** [comment]
I see PR #30 has been merged but the issue is still occurring, I assume this is because there hasn't yet been a new release. Is the plan to do a new release sometime soon?

**Comment by averikitsch** [comment]
I apologize @rickkln , I haven't rebuilt and released the new version yet due to PR #31 . I can ping this thread once released.

**Comment by rickkln** [comment]
No stress! We are deploying manually for now so not the end of the world 🙂

A ping on this thread would be great, thank you 👍
